const ProductData = [
  //Kids
  {
    id: 1,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/71BiQcsnzJL._AC_UL480_FMwebp_QL65_.jpg",
    price: 457.0,
  },
  {
    id: 2,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/6134gSS8j6L._AC_UL480_FMwebp_QL65_.jpg",
    price: 499,
  },
  {
    id: 3,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/81Lv0joTaRL._AC_UL480_FMwebp_QL65_.jpg",
    price: 1299,
  },
  {
    id: 4,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/61ID9h48xqL._AC_UL480_FMwebp_QL65_.jpg",
    price: 599,
  },
  {
    id: 5,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/61vF5YxGOPL._AC_UL480_QL65_.jpg",
    price: 499,
  },
  {
    id: 6,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/61VtST6cgBL._AC_UL480_QL65_.jpg",
    price: 399,
  },
  {
    id: 7,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/61jSmXhGVdL._AC_UL480_QL65_.jpg",
    price: 1599,
  },
  {
    id: 8,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/51pUK5sBOSL._AC_UL480_FMwebp_QL65_.jpg",
    price: 799,
  },
  {
    id: 9,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/41DlQF2nC9L._AC_UL480_QL65_.jpg",
    price: 299,
  },
  {
    id: 10,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/61Lushz-26L._AC_UL480_FMwebp_QL65_.jpg",
    price: 1099,
  },
  {
    id: 11,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/81GLNCj1e1L._AC_UL480_FMwebp_QL65_.jpg",
    price: 399,
  },
  {
    id: 12,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/71FG3D94lGL._AC_UL480_FMwebp_QL65_.jpg",
    price: 899,
  },
  {
    id: 13,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/91xljh1pU6L._AC_UL480_FMwebp_QL65_.jpg",
    price: 699,
  },
  {
    id: 14,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/71yP0q1KX9L._AC_UL480_FMwebp_QL65_.jpg",
    price: 453,
  },
  {
    id: 15,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/71Gsc2AUGUL._AC_UL480_FMwebp_QL65_.jpg",
    price: 499,
  },
  {
    id: 16,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/A12Tol+JE0L._AC_UL480_FMwebp_QL65_.jpg",
    price: 599,
  },
  {
    id: 17,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/61d5lrRh-lL._AC_UL480_FMwebp_QL65_.jpg",
    price: 521,
  },
  {
    id: 18,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/41nCpA27SGS._AC_UL480_FMwebp_QL65_.jpg",
    price: 379,
  },
  {
    id: 19,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/81JT9znqs0L._AC_UL480_FMwebp_QL65_.jpg",
    price: 349,
  },
  {
    id: 20,
    title: "Kids Cloting",
    img: "https://m.media-amazon.com/images/I/41s419jyoCL._AC_UL480_FMwebp_QL65_.jpg",
    price: 399,
  },
  //Men
  {
    id: 21,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/811vZ9A3mqL._AC_UL480_FMwebp_QL65_.jpg",
    price: 399,
  },
  {
    id: 22,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/71rON351gdL._AC_UL480_FMwebp_QL65_.jpg",
    price: 659,
  },
  {
    id: 23,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/71bDzgBQPZL._AC_UL480_FMwebp_QL65_.jpg",
    price: 759,
  },
  {
    id: 24,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/710GszJWzBS._AC_UL480_FMwebp_QL65_.jpg",
    price: 350,
  },
  {
    id: 25,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/815EsKQch7L._AC_UL480_FMwebp_QL65_.jpg",
    price: 680,
  },
  {
    id: 26,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/61+T54SqTpL._AC_UL480_FMwebp_QL65_.jpg",
    price: 857,
  },
  {
    id: 27,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/41lGFbQtc5L._AC_UL480_FMwebp_QL65_.jpg",
    price: 599,
  },
  {
    id: 28,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/71zOvoKpVML._AC_UL480_FMwebp_QL65_.jpg",
    price: 1599,
  },
  {
    id: 29,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/61oTB9F5y0L._AC_UL480_FMwebp_QL65_.jpg",
    price: 1500,
  },
  {
    id: 30,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/61r81T8faQL._AC_UL480_FMwebp_QL65_.jpg",
    price: 599,
  },
  {
    id: 31,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/811vZ9A3mqL._AC_UL480_FMwebp_QL65_.jpg",
    price: 399,
  },
  {
    id: 32,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/71rON351gdL._AC_UL480_FMwebp_QL65_.jpg",
    price: 659,
  },
  {
    id: 33,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/71bDzgBQPZL._AC_UL480_FMwebp_QL65_.jpg",
    price: 759,
  },
  {
    id: 34,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/710GszJWzBS._AC_UL480_FMwebp_QL65_.jpg",
    price: 350,
  },
  {
    id: 35,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/815EsKQch7L._AC_UL480_FMwebp_QL65_.jpg",
    price: 680,
  },
  {
    id: 36,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/61+T54SqTpL._AC_UL480_FMwebp_QL65_.jpg",
    price: 857,
  },
  {
    id: 37,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/41lGFbQtc5L._AC_UL480_FMwebp_QL65_.jpg",
    price: 599,
  },
  {
    id: 38,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/71zOvoKpVML._AC_UL480_FMwebp_QL65_.jpg",
    price: 1599,
  },
  {
    id: 39,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/61oTB9F5y0L._AC_UL480_FMwebp_QL65_.jpg",
    price: 1500,
  },
  //Women
  {
    id: 40,
    title: "Men Cloting",
    img: "https://m.media-amazon.com/images/I/61r81T8faQL._AC_UL480_FMwebp_QL65_.jpg",
    price: 599,
  },
  {
    id: 41,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/61OVY9tLuvL._AC_UL480_FMwebp_QL65_.jpg",
    price: 399,
  },
  {
    id: 42,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/81ntDWA4ViL._AC_UL480_FMwebp_QL65_.jpg",
    price: 659,
  },
  {
    id: 43,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/810V+wvcCJL._AC_UL480_FMwebp_QL65_.jpg",
    price: 759,
  },
  {
    id: 44,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/71P-qc+vyML._AC_UL480_FMwebp_QL65_.jpg",
    price: 350,
  },
  {
    id: 45,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/61KzT2OrERL._AC_UL480_FMwebp_QL65_.jpg",
    price: 680,
  },
  {
    id: 46,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/71Xy186ZyYL._AC_UL480_FMwebp_QL65_.jpg",
    price: 857,
  },
  {
    id: 47,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/61tUk1maVuL._AC_UL480_FMwebp_QL65_.jpg",
    price: 599,
  },
  {
    id: 48,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/61Wfq81WBlL._AC_UL480_QL65_.jpg",
    price: 1599,
  },
  {
    id: 49,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/81Sm8s25SQL._AC_UL480_QL65_.jpg",
    price: 1500,
  },
  {
    id: 50,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/41+s2TxNf6L._AC_UL480_FMwebp_QL65_.jpg",
    price: 599,
  },
  {
    id: 51,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/71EvrbzkhCL._AC_UL480_FMwebp_QL65_.jpg",
    price: 599,
  },
  {
    id: 52,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/71VrwxwQfpL._AC_UL480_FMwebp_QL65_.jpg",
    price: 399,
  },
  {
    id: 53,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/71uUSbJd90L._AC_UL480_FMwebp_QL65_.jpg",
    price: 659,
  },
  {
    id: 54,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/71gVr0ZP2sL._AC_UL480_FMwebp_QL65_.jpg",
    price: 759,
  },
  {
    id: 54,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/81kDI4r4jkL._AC_UL480_FMwebp_QL65_.jpg",
    price: 350,
  },
  {
    id: 55,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/61XUqWtxRsL._AC_UL480_FMwebp_QL65_.jpg",
    price: 680,
  },
  {
    id: 56,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/81CqpfspSkL._AC_UL480_FMwebp_QL65_.jpg",
    price: 857,
  },
  {
    id: 57,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/51yW2HeFTkL._AC_UL480_FMwebp_QL65_.jpg",
    price: 599,
  },
  {
    id: 58,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/91+mgjQeI0L._AC_UL480_FMwebp_QL65_.jpg",
    price: 1599,
  },
  {
    id: 59,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/61l-NI3IXIL._AC_UL480_FMwebp_QL65_.jpg",
    price: 1500,
  },

  {
    id: 60,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/51DoJVdSLWL._AC_UL480_FMwebp_QL65_.jpg",
    price: 599,
  },
  {
    id: 61,
    title: "Women Cloting",
    img: "https://m.media-amazon.com/images/I/51DoJVdSLWL._AC_UL480_FMwebp_QL65_.jpg",
    price: 599,
  },
];
export default ProductData;
